# NUMPY

In [9]:
import numpy as np

In [10]:
## creating array using numpy
## creating a 1D array
arr1 = np.array([1, 2, 3, 4, 5, 6])
print(arr1)

[1 2 3 4 5 6]


In [11]:
type(arr1)

numpy.ndarray

In [13]:
print(arr1.shape)

(6,)


In [25]:
arr2 = np.array([1, 2, 3, 4, 5])
arr2.reshape(1, 5)

array([[1, 2, 3, 4, 5]])

In [26]:
arr3 =  np.array([[1, 2, 3, 4, 5, ]])
print(arr3)

[[1 2 3 4 5]]
