# NUMPY

In [4]:
import numpy as np

In [8]:
## creating array using numpy
## creating a 1D array
arr1 = np.array([1, 2, 3, 4, 5, 6])
print(arr1)

[1 2 3 4 5 6]


In [11]:
type(arr1)

numpy.ndarray

In [13]:
print(arr1.shape)

(6,)


In [25]:
arr2 = np.array([1, 2, 3, 4, 5])
arr2.reshape(1, 5)

array([[1, 2, 3, 4, 5]])

In [5]:
arr3 =  np.array([[1, 2, 3, 4, 5, ]])
print(arr3)

[[1 2 3 4 5]]


In [7]:
print(type(arr3))

<class 'numpy.ndarray'>


In [9]:
print(arr1.shape)

(6,)


In [12]:
arr2 = np.array([1, 2, 3, 4, 5])
print(arr2.reshape((1, 5)))

[[1 2 3 4 5]]


In [13]:
arr2 = np.array([1, 2, 3, 4, 5])
print(arr2.reshape((1, 4)))

ValueError: cannot reshape array of size 5 into shape (1,4)

In [15]:
arr2 = np.array([[1, 2, 3, 4, 5]])
print(arr2)
print(arr2.shape)

[[1 2 3 4 5]]
(1, 5)


In [16]:
arr2 = np.array([[1, 2, 3, 4, 5], [2, 3, 4, 5, 6]])
print(arr2)
print(arr2.shape)


[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


In [18]:
np.arange(0, 10, 2).reshape(5, 1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [19]:
np.arange(0, 10, 2).reshape(1, 5)

array([[0, 2, 4, 6, 8]])

In [21]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [22]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
## attribute of numpy array
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print('Array\n', arr)
print('shape:', arr.shape)
print('Number of dimension:', arr.ndim)
print('size(no of elemnt):', arr.size)
print('Data type:', arr.dtype)
print('Itemsize in byte:', arr.itemsize)

Array
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
shape: (2, 5)
Number of dimension: 2
size(no of elemnt): 10
Data type: int64
Itemsize in byte: 8


In [28]:
## Numpy vectorissed operation
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([10, 20, 30, 40, 50])
## element wise addition
print('Addition:', arr1 + arr2)
## element wise substraction
print('Substraction:', arr2 - arr1)
## Element wise multiplication
print('Multiplication:', arr1 * arr2)
print('Division:', arr1 / arr2)

Addition: [11 22 33 44 55]
Substraction: [ 9 18 27 36 45]
Multiplication: [ 10  40  90 160 250]
Division: [0.1 0.1 0.1 0.1 0.1]


In [31]:
##universal function -> some function that are applied to the entire array
arr = np.array([1, 2, 3, 4, 5, 6])
## square root
print('Square root:', np.sqrt(arr))
## sine
print(np.sin(arr))
## exponential
print(np.exp(arr))
## Natural log 
print(np.log(arr))

Square root: [1.         1.41421356 1.73205081 2.         2.23606798 2.44948974]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591
 403.42879349]
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [33]:
## Slicing and indexing
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]])
print("Array:\n", arr)

Array:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [35]:
print(arr[0][0])

1


In [37]:
print(arr[0])

[1 2 3 4 5]


In [38]:
print(arr[1: ])

[[ 6  7  8  9 10]
 [11 12 13 14 15]]


In [39]:
print(arr[1:, 2: ])

[[ 8  9 10]
 [13 14 15]]


In [41]:
print(arr[0:2])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [43]:
print(arr[0:2, 3:])

[[ 4  5]
 [ 9 10]]


In [49]:
#This code snippet is attempting to slice a list twice.
print(arr[0:2, 3:])

[[ 4  5]
 [ 9 10]]


In [ ]:
print(arr[[0, 2],[2, ]])

[ 3 13]


In [58]:
print(arr[:2, [3, 4]])

[[ 4  5]
 [ 9 10]]


In [59]:
print(arr[1:, 1:3])

[[ 7  8]
 [12 13]]


In [60]:

## Modify element
arr[0,0] = 100
print(arr)

[[100   2   3   4   5]
 [  6   7   8   9  10]
 [ 11  12  13  14  15]]


In [61]:
arr[1:] = 100

In [62]:
print(arr)


[[100   2   3   4   5]
 [100 100 100 100 100]
 [100 100 100 100 100]]


In [63]:
## Statical calculation Normalisation
data = np.array([1, 2, 3, 4, 5])
cal_mean = np.mean(data)

In [64]:
print(cal_mean)


3.0


In [65]:
std_dev = np.std(data)
print(std_dev)

1.4142135623730951


In [67]:
normalised_data = (data - cal_mean) / std_dev
print(normalised_data)

[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [69]:
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
mean = np.mean(data)
median = np.median(data)
var = np.var(data)
print('Mean:', mean)
print('Median:', median)
print('Variance:', var)

Mean: 5.5
Median: 5.5
Variance: 8.25


In [72]:
## Logical opertation
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(data[data > 5])

[ 6  7  8  9 10]


In [80]:
print(data[(data >= 5) & (data <= 8)])

[5 6 7 8]


In [81]:
print(data[(data >= 5) | (data <= 8)])

[ 1  2  3  4  5  6  7  8  9 10]
